### ISSUE TITLE
fix name handling logic

### ISSUE THREAD

**Issue by Lashaka** [Guy-S-glitch/House-Finance-Manager#22]
![image](https://github.com/Guy-S-glitch/House-Finance-Manager/assets/69360460/f1034939-7701-4c53-8f4a-0de6972dc369)

**Comment by Guy-S-glitch** [comment]
hello sir.
I'm happy to inform you that your very beautiful name is available to use.
just like how that girl bertha used me.
I thought she was one of a kind but what can you expect from girl from petah tikva
