### ISSUE TITLE
unhandled issue on SetValuesFromParent (null)

### ISSUE THREAD

**Issue by Lashaka** [Guy-S-glitch/House-Finance-Manager#29]
happens when i have no connection to db, and i click on a house 

![image](https://github.com/Guy-S-glitch/House-Finance-Manager/assets/69360460/8c1f47e7-edc4-4486-aefa-90f80a4aeee7)
![image](https://github.com/Guy-S-glitch/House-Finance-Manager/assets/69360460/02c69c5c-afdd-47d3-b722-beb6c4e4a92f)

**Comment by Guy-S-glitch** [comment]
bug fixed 
now if the list is null we'll skip that part
