### ISSUE TITLE
add loader so user wont see ugly page load, but a nice loading screen, spinner maybe

### ISSUE THREAD

**Issue by Lashaka** [Guy-S-glitch/House-Finance-Manager#37]
![image](https://github.com/Guy-S-glitch/House-Finance-Manager/assets/69360460/faa04eee-1579-4a63-968b-6e05d8801aba)

**Comment by Guy-S-glitch** [comment]
![LoadingHouse](https://github.com/Guy-S-glitch/House-Finance-Manager/assets/158782155/d46f2c6b-5c39-48ef-a293-366b9d7805f8)
